// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Sentiment analysis of X posts to generate a happiness index.
 *
 * - analyzeXSentiment - A function that handles the sentiment analysis process.
 * - AnalyzeXSentimentInput - The input type for the analyzeXSentiment function.
 * - AnalyzeXSentimentOutput - The return type for the analyzeXSentiment function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeXSentimentInputSchema = z.object({
  post: z.string().describe('The X post to analyze.'),
});
export type AnalyzeXSentimentInput = z.infer<typeof AnalyzeXSentimentInputSchema>;

const AnalyzeXSentimentOutputSchema = z.object({
  sentimentScore: z.number().describe('The sentiment score of the X post, ranging from -1 (negative) to 1 (positive).'),
  sentimentLabel: z.string().describe('The sentiment label of the X post (positive, negative, or neutral).'),
  summary: z.string().describe('A short summary of the X post and its sentiment.'),
});
export type AnalyzeXSentimentOutput = z.infer<typeof AnalyzeXSentimentOutputSchema>;

export async function analyzeXSentiment(input: AnalyzeXSentimentInput): Promise<AnalyzeXSentimentOutput> {
  return analyzeXSentimentFlow(input);
}

const analyzeXSentimentPrompt = ai.definePrompt({
  name: 'analyzeXSentimentPrompt',
  input: {schema: AnalyzeXSentimentInputSchema},
  output: {schema: AnalyzeXSentimentOutputSchema},
  prompt: `You are a sentiment analysis expert. Analyze the following X post and provide a sentiment score, label, and summary.\n\nX Post: {{{post}}}\n\nConsider these when computing the sentiment score:\n- Use a scale from -1 to 1, where -1 is very negative, 0 is neutral, and 1 is very positive.\n- Consider the context, tone, and intent of the post.
- Pay attention to both explicit and implicit expressions of sentiment.\n\nOutput the sentiment score, label (positive, negative, or neutral), and a summary of the post and its sentiment.`,
});

const analyzeXSentimentFlow = ai.defineFlow(
  {
    name: 'analyzeXSentimentFlow',
    inputSchema: AnalyzeXSentimentInputSchema,
    outputSchema: AnalyzeXSentimentOutputSchema,
  },
  async input => {
    const {output} = await analyzeXSentimentPrompt(input);
    return output!;
  }
);



